### PR TITLE
Add node.js version

### PR DESCRIPTION
**Pull request by alanrice**
Added a node script. Not sure if the Makefile is correct.
For me node is ~3.6s vs python ~6s

### CODE REVIEW

**Comment by samuell** [comment]
Cool, thanks @alanrice !

**Comment by samuell** [comment]
@alanrice Btw, which version of Node are you using? I seem to get pretty slow times now when testing (Node v12.16.1) ...

**Comment by alanrice** [comment]
> @alanrice Btw, which version of Node are you using? I seem to get pretty slow times now when testing (Node v12.16.1) ...

Hmm, I'm using the latest LTS - v14.15.5

**Comment by samuell** [comment]
> > @alanrice Btw, which version of Node are you using? I seem to get pretty slow times now when testing (Node v12.16.1) ...
> 
> Hmm, I'm using the latest LTS - v14.15.5

Ah, found my mistake: I was running the node version shipped with GraalVM :D

Have added a result from the latest LTS now!

**Pull request merged**
