### PR TITLE
Add compiler hints to C.001's outer loop

### PR DESCRIPTION
**Pull request by jmarshall**
Similar to PR #6 for C++.001. Nice spot, @nh13!

### CODE REVIEW

**Comment by jmarshall** [comment]
I'll add to this one to cover c++.001 as well.

**Comment by samuell** [comment]
> I'll add to this one to cover c++.001 as well.

You want me to wait a bit, or should I merge this one in the meanwhile? :slightly_smiling_face:

**Comment by jmarshall** [comment]
Just finished — ready for merging now. Cheers!

**Comment by samuell** [comment]
Thanks! I didn't actually see any improvements here, but maybe as you mentioned on Twitter, my GCC is too old...?

**Comment by jmarshall** [comment]
I think it means even these old GCCs have better branch prediction optimiser heuristics for this code pattern — only Nils's Clang actually needed this hint.

**Pull request merged**
