### PR TITLE
add nim bitwise

### PR DESCRIPTION
**Pull request by mflevine**
Gave a shot at the bitwise implementation in Nim. Im seeing 3 times as fast vs my last solution.

### CODE REVIEW

**Comment by mflevine** [comment]
Compiling with `--passC:"-flto"` also gets ~10% boost also.

**Comment by timotheecour** [comment]
even faster, via zero-copy (and using more idiomatic code in a few places):
```nim
when true:
  import std/[strutils, memfiles]
  proc process(filename: string) =
    var
      input: MemFile
      totals = 0'u64 # represent A/T and C/G as 32 bit ints combined into a 64 bit int
      value: array[low(char)..high(char), uint64] # adder look up table
    value['A'] = 1
    value['T'] = 1
    value['C'] = 1 shl 32 # add shifted 32 bits left
    value['G'] = 1 shl 32

    input = memfiles.open(filename)
    defer: input.close()
    for slice in memSlices(input):
      let str = cast[cstring](slice.data)
      if slice.size > 0 and str[0] != '>':
        for i in 0..<slice.size:
          totals += value[str[i]]

    let
      at = (totals and 0xFFFFFFFF'u).float # get the A/T 32 bits
      gc = (totals shr 32).float # right shift to get the C/G 32 bits
      gcFraction = gc / (gc + at)
    echo formatFloat(gcFraction * 100, ffDecimal, 4)

  when isMainModule:
    process("chry_multiplied.fa")
```

on my machine, with -d:danger, gives 0.44s instead of 0.52

## note
unlike the numbers reported in https://github.com/samuell/gccontent-benchmark, 1.2 vs 1.4 (with original code) made no performance difference and in fact gave same asm (with -d:danger)

**Comment by ghost** [comment]
I feel like @timotheecour's more idiomatic code is nice but I don't think that doing `let str = cast[cstring](slice.data)` is worth it for the same version (maybe version 3 with even more optimization)?

**Comment by timotheecour** [comment]
>  I don't think that doing let str = cast[cstring](slice.data) is worth 

slice.data is a pointer, i'm not sure how else it can work (unless you're saying to have 1 un-optimized version with copy and one with zero-copy, but not sure what would be the point, the optimized version adds just 1 line of code)

**Comment by mflevine** [comment]
I think their point was how much "lower level" does the code need to go for us to consider it a new version. Speed tradeoffs between high level and low level code.

Thank you for contributing, btw!

**Comment by samuell** [comment]
Hi @mflevine! Sorry, have been busy over the last couple of days. Having a look tonight!

**Comment by samuell** [comment]
Many thanks @mflevine & @timotheecour ! Added as two separate versions, for some added comparison, and updated the README with new timings. Merged manually, so closing.

**Pull request merged**
